apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinemarket
spec:
  selector:
    matchLabels:
      app: onlinemarket
  template:
    metadata:
      labels:
        app: onlinemarket
    spec:
      containers:
      - name: onlinemarket
        image: sunil4478/onlinemarket
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
