apiVersion: v1
kind: Pod
metadata:
  name: onlinemarket
  labels:
    name: onlinemarket
spec:
  containers:
  - name: onlinemarket
    image: sunil4478/onlinemarket
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
